set(PD_MAJOR_VERSION 0)
set(PD_MINOR_VERSION 48)
set(PD_BUGFIX_VERSION 0)
set(PD_BUILD_SUFFIX "xpd")
set(PD_TEXT_VERSION_SHORT "${PD_MAJOR_VERSION}.${PD_MINOR_VERSION}.${PD_BUGFIX_VERSION}")
set(PD_TEXT_VERSION_FULL  "${PD_TEXT_VERSION_SHORT}_${PD_BUILD_SUFFIX}")

set(PD_MACOSX_BUNDLE_VERSION ${PD_TEXT_VERSION_SHORT})
set(PD_MACOSX_BUNDLE_SUFFIX "ceammc_${CEAMMC_DISTRIB_VERSION}")

if(APPLE)
   exec_program(sw_vers ARGS -productVersion OUTPUT_VARIABLE MACOSX_VERSION)
   string(REGEX MATCH "[0-9]+.[0-9]+" MACOSX_VERSION ${MACOSX_VERSION})
endif()
